//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 03:50:40 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:opendata:followup:groupoutcomes:qualitymeasures:2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package opendata.followup.groupoutcomes.qualitymeasures._2;
