//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 03:50:40 PM CEST 
//


package opendata.followup.groupoutcomes.qualitymeasures._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PerformingOrganizationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PerformingOrganizationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="performingOrganizationId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}PerformingOrganizationIdType"/&gt;
 *         &lt;element name="performingOrganizationHsaId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="performingOrganizationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="performingOrganizationType" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType"/&gt;
 *         &lt;element name="asOrganizationPartOf" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}PerformingOrganizationType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PerformingOrganizationType", propOrder = {
    "performingOrganizationId",
    "performingOrganizationHsaId",
    "performingOrganizationName",
    "performingOrganizationType",
    "asOrganizationPartOf"
})
@XmlSeeAlso({
    PerformingOrganization.class
})
public class PerformingOrganizationType {

    @XmlElement(required = true)
    protected String performingOrganizationId;
    protected String performingOrganizationHsaId;
    protected String performingOrganizationName;
    @XmlElement(required = true)
    protected CodingType performingOrganizationType;
    protected PerformingOrganizationType asOrganizationPartOf;

    /**
     * Gets the value of the performingOrganizationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerformingOrganizationId() {
        return performingOrganizationId;
    }

    /**
     * Sets the value of the performingOrganizationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerformingOrganizationId(String value) {
        this.performingOrganizationId = value;
    }

    /**
     * Gets the value of the performingOrganizationHsaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerformingOrganizationHsaId() {
        return performingOrganizationHsaId;
    }

    /**
     * Sets the value of the performingOrganizationHsaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerformingOrganizationHsaId(String value) {
        this.performingOrganizationHsaId = value;
    }

    /**
     * Gets the value of the performingOrganizationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerformingOrganizationName() {
        return performingOrganizationName;
    }

    /**
     * Sets the value of the performingOrganizationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerformingOrganizationName(String value) {
        this.performingOrganizationName = value;
    }

    /**
     * Gets the value of the performingOrganizationType property.
     * 
     * @return
     *     possible object is
     *     {@link CodingType }
     *     
     */
    public CodingType getPerformingOrganizationType() {
        return performingOrganizationType;
    }

    /**
     * Sets the value of the performingOrganizationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodingType }
     *     
     */
    public void setPerformingOrganizationType(CodingType value) {
        this.performingOrganizationType = value;
    }

    /**
     * Gets the value of the asOrganizationPartOf property.
     * 
     * @return
     *     possible object is
     *     {@link PerformingOrganizationType }
     *     
     */
    public PerformingOrganizationType getAsOrganizationPartOf() {
        return asOrganizationPartOf;
    }

    /**
     * Sets the value of the asOrganizationPartOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerformingOrganizationType }
     *     
     */
    public void setAsOrganizationPartOf(PerformingOrganizationType value) {
        this.asOrganizationPartOf = value;
    }

}
