//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 03:50:40 PM CEST 
//


package opendata.followup.groupoutcomes.qualitymeasures._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MeasureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasureType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="measureId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}MeasureIdType"/&gt;
 *         &lt;element name="lastUpdated" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="validFrom" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="validTo" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="publiclyAvailableInformation" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="regionalIndicator" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="subCategoryDefinition" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}SubCategoryDefinitionType" minOccurs="0"/&gt;
 *         &lt;element name="parentMeasureDefinition" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ParentMeasureDefinitionType" minOccurs="0"/&gt;
 *         &lt;element name="author" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}AuthorType"/&gt;
 *         &lt;element name="authenticator" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}AuthenticatorType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasureType", propOrder = {
    "measureId",
    "lastUpdated",
    "validFrom",
    "validTo",
    "publiclyAvailableInformation",
    "regionalIndicator",
    "subCategoryDefinition",
    "parentMeasureDefinition",
    "author",
    "authenticator"
})
@XmlSeeAlso({
    Measure.class
})
public class MeasureType {

    @XmlElement(required = true)
    protected String measureId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastUpdated;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar validFrom;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar validTo;
    protected boolean publiclyAvailableInformation;
    protected List<String> regionalIndicator;
    protected SubCategoryDefinitionType subCategoryDefinition;
    protected ParentMeasureDefinitionType parentMeasureDefinition;
    @XmlElement(required = true)
    protected AuthorType author;
    protected AuthenticatorType authenticator;

    /**
     * Gets the value of the measureId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasureId() {
        return measureId;
    }

    /**
     * Sets the value of the measureId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasureId(String value) {
        this.measureId = value;
    }

    /**
     * Gets the value of the lastUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdated() {
        return lastUpdated;
    }

    /**
     * Sets the value of the lastUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdated(XMLGregorianCalendar value) {
        this.lastUpdated = value;
    }

    /**
     * Gets the value of the validFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidFrom() {
        return validFrom;
    }

    /**
     * Sets the value of the validFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidFrom(XMLGregorianCalendar value) {
        this.validFrom = value;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidTo() {
        return validTo;
    }

    /**
     * Sets the value of the validTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidTo(XMLGregorianCalendar value) {
        this.validTo = value;
    }

    /**
     * Gets the value of the publiclyAvailableInformation property.
     * 
     */
    public boolean isPubliclyAvailableInformation() {
        return publiclyAvailableInformation;
    }

    /**
     * Sets the value of the publiclyAvailableInformation property.
     * 
     */
    public void setPubliclyAvailableInformation(boolean value) {
        this.publiclyAvailableInformation = value;
    }

    /**
     * Gets the value of the regionalIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regionalIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegionalIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRegionalIndicator() {
        if (regionalIndicator == null) {
            regionalIndicator = new ArrayList<String>();
        }
        return this.regionalIndicator;
    }

    /**
     * Gets the value of the subCategoryDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link SubCategoryDefinitionType }
     *     
     */
    public SubCategoryDefinitionType getSubCategoryDefinition() {
        return subCategoryDefinition;
    }

    /**
     * Sets the value of the subCategoryDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubCategoryDefinitionType }
     *     
     */
    public void setSubCategoryDefinition(SubCategoryDefinitionType value) {
        this.subCategoryDefinition = value;
    }

    /**
     * Gets the value of the parentMeasureDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link ParentMeasureDefinitionType }
     *     
     */
    public ParentMeasureDefinitionType getParentMeasureDefinition() {
        return parentMeasureDefinition;
    }

    /**
     * Sets the value of the parentMeasureDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentMeasureDefinitionType }
     *     
     */
    public void setParentMeasureDefinition(ParentMeasureDefinitionType value) {
        this.parentMeasureDefinition = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorType }
     *     
     */
    public AuthorType getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorType }
     *     
     */
    public void setAuthor(AuthorType value) {
        this.author = value;
    }

    /**
     * Gets the value of the authenticator property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticatorType }
     *     
     */
    public AuthenticatorType getAuthenticator() {
        return authenticator;
    }

    /**
     * Sets the value of the authenticator property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticatorType }
     *     
     */
    public void setAuthenticator(AuthenticatorType value) {
        this.authenticator = value;
    }

}
