//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 03:50:40 PM CEST 
//


package opendata.followup.groupoutcomes.qualitymeasures._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MeasureFormerVersionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasureFormerVersionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="measureFormerVersionId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}MeasureFormerVersionIdType"/&gt;
 *         &lt;element name="measureId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}MeasureIdType"/&gt;
 *         &lt;element name="measureVersionNumberMajor" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="measureVersionNumberMinor" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="lastUpdated" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="validFrom" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="validTo" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="publiclyAvailableInformation" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="regionalIndicator" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="measureDefinition" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="descriptionSource" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *         &lt;element name="measureTypeCode" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" minOccurs="0"/&gt;
 *         &lt;element name="measurementTypeCode" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" minOccurs="0"/&gt;
 *         &lt;element name="measureGroupCode" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="soughtValue" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" minOccurs="0"/&gt;
 *         &lt;element name="sourcesOfError" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="coverageCalculation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="numeratorDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="numeratorInclusionValueSet" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="numeratorExclusionValueSet" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="denominatorDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="denominatorInclusionValueSet" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="denominatorExclusionValueSet" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="unit" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" minOccurs="0"/&gt;
 *         &lt;element name="measurePopulationDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="measurePopulationInclusionValueSet" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="measurePopulationExclusionValueSet" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="cohortDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cohortInclusionValueSet" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="cohortExclusionValueSet" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="regionalAffinityCalculation" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" minOccurs="0"/&gt;
 *         &lt;element name="thresholdForViewing" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="measuringFrequency" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="organizationLevel" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="interpretationTextPersonell" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="interpretationTextPublic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="availableReportingSystemHsaId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}HsaIdType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="serviceContractVersion" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="author" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}AuthorType"/&gt;
 *         &lt;element name="authenticator" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}AuthenticatorType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasureFormerVersionType", propOrder = {
    "measureFormerVersionId",
    "measureId",
    "measureVersionNumberMajor",
    "measureVersionNumberMinor",
    "lastUpdated",
    "validFrom",
    "validTo",
    "publiclyAvailableInformation",
    "regionalIndicator",
    "title",
    "measureDefinition",
    "description",
    "descriptionSource",
    "measureTypeCode",
    "measurementTypeCode",
    "measureGroupCode",
    "soughtValue",
    "sourcesOfError",
    "coverageCalculation",
    "numeratorDefinition",
    "numeratorInclusionValueSet",
    "numeratorExclusionValueSet",
    "denominatorDefinition",
    "denominatorInclusionValueSet",
    "denominatorExclusionValueSet",
    "unit",
    "measurePopulationDefinition",
    "measurePopulationInclusionValueSet",
    "measurePopulationExclusionValueSet",
    "cohortDefinition",
    "cohortInclusionValueSet",
    "cohortExclusionValueSet",
    "regionalAffinityCalculation",
    "thresholdForViewing",
    "measuringFrequency",
    "organizationLevel",
    "interpretationTextPersonell",
    "interpretationTextPublic",
    "availableReportingSystemHsaId",
    "serviceContractVersion",
    "author",
    "authenticator"
})
@XmlSeeAlso({
    MeasureFormerVersion.class
})
public class MeasureFormerVersionType {

    @XmlElement(required = true)
    protected String measureFormerVersionId;
    @XmlElement(required = true)
    protected String measureId;
    protected int measureVersionNumberMajor;
    protected int measureVersionNumberMinor;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastUpdated;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar validFrom;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar validTo;
    protected boolean publiclyAvailableInformation;
    protected List<String> regionalIndicator;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String measureDefinition;
    protected String description;
    @XmlElement(required = true)
    protected List<String> descriptionSource;
    protected CodingType measureTypeCode;
    protected CodingType measurementTypeCode;
    protected List<CodingType> measureGroupCode;
    protected CodingType soughtValue;
    protected String sourcesOfError;
    protected String coverageCalculation;
    protected String numeratorDefinition;
    protected List<ValueSetType> numeratorInclusionValueSet;
    protected List<ValueSetType> numeratorExclusionValueSet;
    protected String denominatorDefinition;
    protected List<ValueSetType> denominatorInclusionValueSet;
    protected List<ValueSetType> denominatorExclusionValueSet;
    protected CodingType unit;
    protected String measurePopulationDefinition;
    protected List<ValueSetType> measurePopulationInclusionValueSet;
    protected List<ValueSetType> measurePopulationExclusionValueSet;
    protected String cohortDefinition;
    protected List<ValueSetType> cohortInclusionValueSet;
    protected List<ValueSetType> cohortExclusionValueSet;
    protected CodingType regionalAffinityCalculation;
    protected int thresholdForViewing;
    @XmlElement(required = true)
    protected List<CodingType> measuringFrequency;
    @XmlElement(required = true)
    protected List<CodingType> organizationLevel;
    protected String interpretationTextPersonell;
    protected String interpretationTextPublic;
    protected List<String> availableReportingSystemHsaId;
    protected Integer serviceContractVersion;
    @XmlElement(required = true)
    protected AuthorType author;
    protected AuthenticatorType authenticator;

    /**
     * Gets the value of the measureFormerVersionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasureFormerVersionId() {
        return measureFormerVersionId;
    }

    /**
     * Sets the value of the measureFormerVersionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasureFormerVersionId(String value) {
        this.measureFormerVersionId = value;
    }

    /**
     * Gets the value of the measureId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasureId() {
        return measureId;
    }

    /**
     * Sets the value of the measureId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasureId(String value) {
        this.measureId = value;
    }

    /**
     * Gets the value of the measureVersionNumberMajor property.
     * 
     */
    public int getMeasureVersionNumberMajor() {
        return measureVersionNumberMajor;
    }

    /**
     * Sets the value of the measureVersionNumberMajor property.
     * 
     */
    public void setMeasureVersionNumberMajor(int value) {
        this.measureVersionNumberMajor = value;
    }

    /**
     * Gets the value of the measureVersionNumberMinor property.
     * 
     */
    public int getMeasureVersionNumberMinor() {
        return measureVersionNumberMinor;
    }

    /**
     * Sets the value of the measureVersionNumberMinor property.
     * 
     */
    public void setMeasureVersionNumberMinor(int value) {
        this.measureVersionNumberMinor = value;
    }

    /**
     * Gets the value of the lastUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdated() {
        return lastUpdated;
    }

    /**
     * Sets the value of the lastUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdated(XMLGregorianCalendar value) {
        this.lastUpdated = value;
    }

    /**
     * Gets the value of the validFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidFrom() {
        return validFrom;
    }

    /**
     * Sets the value of the validFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidFrom(XMLGregorianCalendar value) {
        this.validFrom = value;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidTo() {
        return validTo;
    }

    /**
     * Sets the value of the validTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidTo(XMLGregorianCalendar value) {
        this.validTo = value;
    }

    /**
     * Gets the value of the publiclyAvailableInformation property.
     * 
     */
    public boolean isPubliclyAvailableInformation() {
        return publiclyAvailableInformation;
    }

    /**
     * Sets the value of the publiclyAvailableInformation property.
     * 
     */
    public void setPubliclyAvailableInformation(boolean value) {
        this.publiclyAvailableInformation = value;
    }

    /**
     * Gets the value of the regionalIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regionalIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegionalIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRegionalIndicator() {
        if (regionalIndicator == null) {
            regionalIndicator = new ArrayList<String>();
        }
        return this.regionalIndicator;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the measureDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasureDefinition() {
        return measureDefinition;
    }

    /**
     * Sets the value of the measureDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasureDefinition(String value) {
        this.measureDefinition = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the descriptionSource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descriptionSource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescriptionSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDescriptionSource() {
        if (descriptionSource == null) {
            descriptionSource = new ArrayList<String>();
        }
        return this.descriptionSource;
    }

    /**
     * Gets the value of the measureTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodingType }
     *     
     */
    public CodingType getMeasureTypeCode() {
        return measureTypeCode;
    }

    /**
     * Sets the value of the measureTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodingType }
     *     
     */
    public void setMeasureTypeCode(CodingType value) {
        this.measureTypeCode = value;
    }

    /**
     * Gets the value of the measurementTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodingType }
     *     
     */
    public CodingType getMeasurementTypeCode() {
        return measurementTypeCode;
    }

    /**
     * Sets the value of the measurementTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodingType }
     *     
     */
    public void setMeasurementTypeCode(CodingType value) {
        this.measurementTypeCode = value;
    }

    /**
     * Gets the value of the measureGroupCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measureGroupCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasureGroupCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodingType }
     * 
     * 
     */
    public List<CodingType> getMeasureGroupCode() {
        if (measureGroupCode == null) {
            measureGroupCode = new ArrayList<CodingType>();
        }
        return this.measureGroupCode;
    }

    /**
     * Gets the value of the soughtValue property.
     * 
     * @return
     *     possible object is
     *     {@link CodingType }
     *     
     */
    public CodingType getSoughtValue() {
        return soughtValue;
    }

    /**
     * Sets the value of the soughtValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodingType }
     *     
     */
    public void setSoughtValue(CodingType value) {
        this.soughtValue = value;
    }

    /**
     * Gets the value of the sourcesOfError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcesOfError() {
        return sourcesOfError;
    }

    /**
     * Sets the value of the sourcesOfError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcesOfError(String value) {
        this.sourcesOfError = value;
    }

    /**
     * Gets the value of the coverageCalculation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverageCalculation() {
        return coverageCalculation;
    }

    /**
     * Sets the value of the coverageCalculation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverageCalculation(String value) {
        this.coverageCalculation = value;
    }

    /**
     * Gets the value of the numeratorDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeratorDefinition() {
        return numeratorDefinition;
    }

    /**
     * Sets the value of the numeratorDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeratorDefinition(String value) {
        this.numeratorDefinition = value;
    }

    /**
     * Gets the value of the numeratorInclusionValueSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the numeratorInclusionValueSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNumeratorInclusionValueSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueSetType }
     * 
     * 
     */
    public List<ValueSetType> getNumeratorInclusionValueSet() {
        if (numeratorInclusionValueSet == null) {
            numeratorInclusionValueSet = new ArrayList<ValueSetType>();
        }
        return this.numeratorInclusionValueSet;
    }

    /**
     * Gets the value of the numeratorExclusionValueSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the numeratorExclusionValueSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNumeratorExclusionValueSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueSetType }
     * 
     * 
     */
    public List<ValueSetType> getNumeratorExclusionValueSet() {
        if (numeratorExclusionValueSet == null) {
            numeratorExclusionValueSet = new ArrayList<ValueSetType>();
        }
        return this.numeratorExclusionValueSet;
    }

    /**
     * Gets the value of the denominatorDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominatorDefinition() {
        return denominatorDefinition;
    }

    /**
     * Sets the value of the denominatorDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominatorDefinition(String value) {
        this.denominatorDefinition = value;
    }

    /**
     * Gets the value of the denominatorInclusionValueSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the denominatorInclusionValueSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDenominatorInclusionValueSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueSetType }
     * 
     * 
     */
    public List<ValueSetType> getDenominatorInclusionValueSet() {
        if (denominatorInclusionValueSet == null) {
            denominatorInclusionValueSet = new ArrayList<ValueSetType>();
        }
        return this.denominatorInclusionValueSet;
    }

    /**
     * Gets the value of the denominatorExclusionValueSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the denominatorExclusionValueSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDenominatorExclusionValueSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueSetType }
     * 
     * 
     */
    public List<ValueSetType> getDenominatorExclusionValueSet() {
        if (denominatorExclusionValueSet == null) {
            denominatorExclusionValueSet = new ArrayList<ValueSetType>();
        }
        return this.denominatorExclusionValueSet;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link CodingType }
     *     
     */
    public CodingType getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodingType }
     *     
     */
    public void setUnit(CodingType value) {
        this.unit = value;
    }

    /**
     * Gets the value of the measurePopulationDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurePopulationDefinition() {
        return measurePopulationDefinition;
    }

    /**
     * Sets the value of the measurePopulationDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurePopulationDefinition(String value) {
        this.measurePopulationDefinition = value;
    }

    /**
     * Gets the value of the measurePopulationInclusionValueSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measurePopulationInclusionValueSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasurePopulationInclusionValueSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueSetType }
     * 
     * 
     */
    public List<ValueSetType> getMeasurePopulationInclusionValueSet() {
        if (measurePopulationInclusionValueSet == null) {
            measurePopulationInclusionValueSet = new ArrayList<ValueSetType>();
        }
        return this.measurePopulationInclusionValueSet;
    }

    /**
     * Gets the value of the measurePopulationExclusionValueSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measurePopulationExclusionValueSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasurePopulationExclusionValueSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueSetType }
     * 
     * 
     */
    public List<ValueSetType> getMeasurePopulationExclusionValueSet() {
        if (measurePopulationExclusionValueSet == null) {
            measurePopulationExclusionValueSet = new ArrayList<ValueSetType>();
        }
        return this.measurePopulationExclusionValueSet;
    }

    /**
     * Gets the value of the cohortDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCohortDefinition() {
        return cohortDefinition;
    }

    /**
     * Sets the value of the cohortDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCohortDefinition(String value) {
        this.cohortDefinition = value;
    }

    /**
     * Gets the value of the cohortInclusionValueSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cohortInclusionValueSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCohortInclusionValueSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueSetType }
     * 
     * 
     */
    public List<ValueSetType> getCohortInclusionValueSet() {
        if (cohortInclusionValueSet == null) {
            cohortInclusionValueSet = new ArrayList<ValueSetType>();
        }
        return this.cohortInclusionValueSet;
    }

    /**
     * Gets the value of the cohortExclusionValueSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cohortExclusionValueSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCohortExclusionValueSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueSetType }
     * 
     * 
     */
    public List<ValueSetType> getCohortExclusionValueSet() {
        if (cohortExclusionValueSet == null) {
            cohortExclusionValueSet = new ArrayList<ValueSetType>();
        }
        return this.cohortExclusionValueSet;
    }

    /**
     * Gets the value of the regionalAffinityCalculation property.
     * 
     * @return
     *     possible object is
     *     {@link CodingType }
     *     
     */
    public CodingType getRegionalAffinityCalculation() {
        return regionalAffinityCalculation;
    }

    /**
     * Sets the value of the regionalAffinityCalculation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodingType }
     *     
     */
    public void setRegionalAffinityCalculation(CodingType value) {
        this.regionalAffinityCalculation = value;
    }

    /**
     * Gets the value of the thresholdForViewing property.
     * 
     */
    public int getThresholdForViewing() {
        return thresholdForViewing;
    }

    /**
     * Sets the value of the thresholdForViewing property.
     * 
     */
    public void setThresholdForViewing(int value) {
        this.thresholdForViewing = value;
    }

    /**
     * Gets the value of the measuringFrequency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measuringFrequency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasuringFrequency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodingType }
     * 
     * 
     */
    public List<CodingType> getMeasuringFrequency() {
        if (measuringFrequency == null) {
            measuringFrequency = new ArrayList<CodingType>();
        }
        return this.measuringFrequency;
    }

    /**
     * Gets the value of the organizationLevel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizationLevel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganizationLevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodingType }
     * 
     * 
     */
    public List<CodingType> getOrganizationLevel() {
        if (organizationLevel == null) {
            organizationLevel = new ArrayList<CodingType>();
        }
        return this.organizationLevel;
    }

    /**
     * Gets the value of the interpretationTextPersonell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterpretationTextPersonell() {
        return interpretationTextPersonell;
    }

    /**
     * Sets the value of the interpretationTextPersonell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterpretationTextPersonell(String value) {
        this.interpretationTextPersonell = value;
    }

    /**
     * Gets the value of the interpretationTextPublic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterpretationTextPublic() {
        return interpretationTextPublic;
    }

    /**
     * Sets the value of the interpretationTextPublic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterpretationTextPublic(String value) {
        this.interpretationTextPublic = value;
    }

    /**
     * Gets the value of the availableReportingSystemHsaId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the availableReportingSystemHsaId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvailableReportingSystemHsaId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAvailableReportingSystemHsaId() {
        if (availableReportingSystemHsaId == null) {
            availableReportingSystemHsaId = new ArrayList<String>();
        }
        return this.availableReportingSystemHsaId;
    }

    /**
     * Gets the value of the serviceContractVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getServiceContractVersion() {
        return serviceContractVersion;
    }

    /**
     * Sets the value of the serviceContractVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setServiceContractVersion(Integer value) {
        this.serviceContractVersion = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorType }
     *     
     */
    public AuthorType getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorType }
     *     
     */
    public void setAuthor(AuthorType value) {
        this.author = value;
    }

    /**
     * Gets the value of the authenticator property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticatorType }
     *     
     */
    public AuthenticatorType getAuthenticator() {
        return authenticator;
    }

    /**
     * Sets the value of the authenticator property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticatorType }
     *     
     */
    public void setAuthenticator(AuthenticatorType value) {
        this.authenticator = value;
    }

}
