//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 03:50:40 PM CEST 
//


package opendata.followup.groupoutcomes.qualitymeasures._2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the opendata.followup.groupoutcomes.qualitymeasures._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: opendata.followup.groupoutcomes.qualitymeasures._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Measures }
     * 
     */
    public Measures createMeasures() {
        return new Measures();
    }

    /**
     * Create an instance of {@link MeasureType }
     * 
     */
    public MeasureType createMeasureType() {
        return new MeasureType();
    }

    /**
     * Create an instance of {@link Measure }
     * 
     */
    public Measure createMeasure() {
        return new Measure();
    }

    /**
     * Create an instance of {@link SubCategoryDefinitionType }
     * 
     */
    public SubCategoryDefinitionType createSubCategoryDefinitionType() {
        return new SubCategoryDefinitionType();
    }

    /**
     * Create an instance of {@link ParentMeasureDefinitionType }
     * 
     */
    public ParentMeasureDefinitionType createParentMeasureDefinitionType() {
        return new ParentMeasureDefinitionType();
    }

    /**
     * Create an instance of {@link AuthorType }
     * 
     */
    public AuthorType createAuthorType() {
        return new AuthorType();
    }

    /**
     * Create an instance of {@link AuthenticatorType }
     * 
     */
    public AuthenticatorType createAuthenticatorType() {
        return new AuthenticatorType();
    }

    /**
     * Create an instance of {@link MeasureFormerVersions }
     * 
     */
    public MeasureFormerVersions createMeasureFormerVersions() {
        return new MeasureFormerVersions();
    }

    /**
     * Create an instance of {@link MeasureFormerVersionType }
     * 
     */
    public MeasureFormerVersionType createMeasureFormerVersionType() {
        return new MeasureFormerVersionType();
    }

    /**
     * Create an instance of {@link MeasureFormerVersion }
     * 
     */
    public MeasureFormerVersion createMeasureFormerVersion() {
        return new MeasureFormerVersion();
    }

    /**
     * Create an instance of {@link CodingType }
     * 
     */
    public CodingType createCodingType() {
        return new CodingType();
    }

    /**
     * Create an instance of {@link ValueSetType }
     * 
     */
    public ValueSetType createValueSetType() {
        return new ValueSetType();
    }

    /**
     * Create an instance of {@link PerformingOrganizations }
     * 
     */
    public PerformingOrganizations createPerformingOrganizations() {
        return new PerformingOrganizations();
    }

    /**
     * Create an instance of {@link PerformingOrganizationType }
     * 
     */
    public PerformingOrganizationType createPerformingOrganizationType() {
        return new PerformingOrganizationType();
    }

    /**
     * Create an instance of {@link PerformingOrganization }
     * 
     */
    public PerformingOrganization createPerformingOrganization() {
        return new PerformingOrganization();
    }

    /**
     * Create an instance of {@link ValueSet }
     * 
     */
    public ValueSet createValueSet() {
        return new ValueSet();
    }

    /**
     * Create an instance of {@link ValueSets }
     * 
     */
    public ValueSets createValueSets() {
        return new ValueSets();
    }

    /**
     * Create an instance of {@link TargetMeasurement }
     * 
     */
    public TargetMeasurement createTargetMeasurement() {
        return new TargetMeasurement();
    }

    /**
     * Create an instance of {@link TargetMeasurementType }
     * 
     */
    public TargetMeasurementType createTargetMeasurementType() {
        return new TargetMeasurementType();
    }

    /**
     * Create an instance of {@link TargetProportionMeasureType }
     * 
     */
    public TargetProportionMeasureType createTargetProportionMeasureType() {
        return new TargetProportionMeasureType();
    }

    /**
     * Create an instance of {@link TargetContinuousMeasureType }
     * 
     */
    public TargetContinuousMeasureType createTargetContinuousMeasureType() {
        return new TargetContinuousMeasureType();
    }

    /**
     * Create an instance of {@link TargetCohortMeasureType }
     * 
     */
    public TargetCohortMeasureType createTargetCohortMeasureType() {
        return new TargetCohortMeasureType();
    }

    /**
     * Create an instance of {@link TargetMeasurements }
     * 
     */
    public TargetMeasurements createTargetMeasurements() {
        return new TargetMeasurements();
    }

    /**
     * Create an instance of {@link CodeSystem }
     * 
     */
    public CodeSystem createCodeSystem() {
        return new CodeSystem();
    }

    /**
     * Create an instance of {@link CodeSystemType }
     * 
     */
    public CodeSystemType createCodeSystemType() {
        return new CodeSystemType();
    }

    /**
     * Create an instance of {@link CodeSystems }
     * 
     */
    public CodeSystems createCodeSystems() {
        return new CodeSystems();
    }

    /**
     * Create an instance of {@link Code }
     * 
     */
    public Code createCode() {
        return new Code();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link Codes }
     * 
     */
    public Codes createCodes() {
        return new Codes();
    }

}
