//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 03:50:40 PM CEST 
//


package opendata.followup.groupoutcomes.qualitymeasures._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParentMeasureDefinitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParentMeasureDefinitionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="measureVersionNumberMajor" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="measureVersionNumberMinor" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="measureDefinition" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="descriptionSource" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *         &lt;element name="measureTypeCode" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" minOccurs="0"/&gt;
 *         &lt;element name="measurementTypeCode" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" minOccurs="0"/&gt;
 *         &lt;element name="measureGroupCode" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="soughtValue" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" minOccurs="0"/&gt;
 *         &lt;element name="sourcesOfError" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="coverageCalculation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="numeratorDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="numeratorInclusionValueSetId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetIdType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="numeratorExclusionValueSetId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetIdType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="denominatorDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="denominatorInclusionValueSetId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetIdType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="denominatorExclusionValueSetId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetIdType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="unit" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" minOccurs="0"/&gt;
 *         &lt;element name="measurePopulationDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="measurePopulationInclusionValueSetId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetIdType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="measurePopulationExclusionValueSetId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetIdType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="cohortDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cohortInclusionValueSetsId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetIdType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="cohortExclusionValueSetsId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}ValueSetIdType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="regionalAffinityCalculation" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" minOccurs="0"/&gt;
 *         &lt;element name="thresholdForViewing" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="measuringFrequency" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="organizationLevel" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="interpretationTextPersonell" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="interpretationTextPublic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="availableReportingSystemHsaId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}HsaIdType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="serviceContractVersion" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParentMeasureDefinitionType", propOrder = {
    "measureVersionNumberMajor",
    "measureVersionNumberMinor",
    "title",
    "measureDefinition",
    "description",
    "descriptionSource",
    "measureTypeCode",
    "measurementTypeCode",
    "measureGroupCode",
    "soughtValue",
    "sourcesOfError",
    "coverageCalculation",
    "numeratorDefinition",
    "numeratorInclusionValueSetId",
    "numeratorExclusionValueSetId",
    "denominatorDefinition",
    "denominatorInclusionValueSetId",
    "denominatorExclusionValueSetId",
    "unit",
    "measurePopulationDefinition",
    "measurePopulationInclusionValueSetId",
    "measurePopulationExclusionValueSetId",
    "cohortDefinition",
    "cohortInclusionValueSetsId",
    "cohortExclusionValueSetsId",
    "regionalAffinityCalculation",
    "thresholdForViewing",
    "measuringFrequency",
    "organizationLevel",
    "interpretationTextPersonell",
    "interpretationTextPublic",
    "availableReportingSystemHsaId",
    "serviceContractVersion"
})
public class ParentMeasureDefinitionType {

    protected int measureVersionNumberMajor;
    protected int measureVersionNumberMinor;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String measureDefinition;
    protected String description;
    @XmlElement(required = true)
    protected List<String> descriptionSource;
    protected CodingType measureTypeCode;
    protected CodingType measurementTypeCode;
    protected List<CodingType> measureGroupCode;
    protected CodingType soughtValue;
    protected String sourcesOfError;
    protected String coverageCalculation;
    protected String numeratorDefinition;
    protected List<String> numeratorInclusionValueSetId;
    protected List<String> numeratorExclusionValueSetId;
    protected String denominatorDefinition;
    protected List<String> denominatorInclusionValueSetId;
    protected List<String> denominatorExclusionValueSetId;
    protected CodingType unit;
    protected String measurePopulationDefinition;
    protected List<String> measurePopulationInclusionValueSetId;
    protected List<String> measurePopulationExclusionValueSetId;
    protected String cohortDefinition;
    protected List<String> cohortInclusionValueSetsId;
    protected List<String> cohortExclusionValueSetsId;
    protected CodingType regionalAffinityCalculation;
    protected int thresholdForViewing;
    @XmlElement(required = true)
    protected List<CodingType> measuringFrequency;
    @XmlElement(required = true)
    protected List<CodingType> organizationLevel;
    protected String interpretationTextPersonell;
    protected String interpretationTextPublic;
    protected List<String> availableReportingSystemHsaId;
    protected Integer serviceContractVersion;

    /**
     * Gets the value of the measureVersionNumberMajor property.
     * 
     */
    public int getMeasureVersionNumberMajor() {
        return measureVersionNumberMajor;
    }

    /**
     * Sets the value of the measureVersionNumberMajor property.
     * 
     */
    public void setMeasureVersionNumberMajor(int value) {
        this.measureVersionNumberMajor = value;
    }

    /**
     * Gets the value of the measureVersionNumberMinor property.
     * 
     */
    public int getMeasureVersionNumberMinor() {
        return measureVersionNumberMinor;
    }

    /**
     * Sets the value of the measureVersionNumberMinor property.
     * 
     */
    public void setMeasureVersionNumberMinor(int value) {
        this.measureVersionNumberMinor = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the measureDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasureDefinition() {
        return measureDefinition;
    }

    /**
     * Sets the value of the measureDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasureDefinition(String value) {
        this.measureDefinition = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the descriptionSource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descriptionSource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescriptionSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDescriptionSource() {
        if (descriptionSource == null) {
            descriptionSource = new ArrayList<String>();
        }
        return this.descriptionSource;
    }

    /**
     * Gets the value of the measureTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodingType }
     *     
     */
    public CodingType getMeasureTypeCode() {
        return measureTypeCode;
    }

    /**
     * Sets the value of the measureTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodingType }
     *     
     */
    public void setMeasureTypeCode(CodingType value) {
        this.measureTypeCode = value;
    }

    /**
     * Gets the value of the measurementTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodingType }
     *     
     */
    public CodingType getMeasurementTypeCode() {
        return measurementTypeCode;
    }

    /**
     * Sets the value of the measurementTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodingType }
     *     
     */
    public void setMeasurementTypeCode(CodingType value) {
        this.measurementTypeCode = value;
    }

    /**
     * Gets the value of the measureGroupCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measureGroupCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasureGroupCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodingType }
     * 
     * 
     */
    public List<CodingType> getMeasureGroupCode() {
        if (measureGroupCode == null) {
            measureGroupCode = new ArrayList<CodingType>();
        }
        return this.measureGroupCode;
    }

    /**
     * Gets the value of the soughtValue property.
     * 
     * @return
     *     possible object is
     *     {@link CodingType }
     *     
     */
    public CodingType getSoughtValue() {
        return soughtValue;
    }

    /**
     * Sets the value of the soughtValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodingType }
     *     
     */
    public void setSoughtValue(CodingType value) {
        this.soughtValue = value;
    }

    /**
     * Gets the value of the sourcesOfError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcesOfError() {
        return sourcesOfError;
    }

    /**
     * Sets the value of the sourcesOfError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcesOfError(String value) {
        this.sourcesOfError = value;
    }

    /**
     * Gets the value of the coverageCalculation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverageCalculation() {
        return coverageCalculation;
    }

    /**
     * Sets the value of the coverageCalculation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverageCalculation(String value) {
        this.coverageCalculation = value;
    }

    /**
     * Gets the value of the numeratorDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeratorDefinition() {
        return numeratorDefinition;
    }

    /**
     * Sets the value of the numeratorDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeratorDefinition(String value) {
        this.numeratorDefinition = value;
    }

    /**
     * Gets the value of the numeratorInclusionValueSetId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the numeratorInclusionValueSetId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNumeratorInclusionValueSetId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNumeratorInclusionValueSetId() {
        if (numeratorInclusionValueSetId == null) {
            numeratorInclusionValueSetId = new ArrayList<String>();
        }
        return this.numeratorInclusionValueSetId;
    }

    /**
     * Gets the value of the numeratorExclusionValueSetId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the numeratorExclusionValueSetId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNumeratorExclusionValueSetId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNumeratorExclusionValueSetId() {
        if (numeratorExclusionValueSetId == null) {
            numeratorExclusionValueSetId = new ArrayList<String>();
        }
        return this.numeratorExclusionValueSetId;
    }

    /**
     * Gets the value of the denominatorDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominatorDefinition() {
        return denominatorDefinition;
    }

    /**
     * Sets the value of the denominatorDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominatorDefinition(String value) {
        this.denominatorDefinition = value;
    }

    /**
     * Gets the value of the denominatorInclusionValueSetId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the denominatorInclusionValueSetId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDenominatorInclusionValueSetId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDenominatorInclusionValueSetId() {
        if (denominatorInclusionValueSetId == null) {
            denominatorInclusionValueSetId = new ArrayList<String>();
        }
        return this.denominatorInclusionValueSetId;
    }

    /**
     * Gets the value of the denominatorExclusionValueSetId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the denominatorExclusionValueSetId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDenominatorExclusionValueSetId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDenominatorExclusionValueSetId() {
        if (denominatorExclusionValueSetId == null) {
            denominatorExclusionValueSetId = new ArrayList<String>();
        }
        return this.denominatorExclusionValueSetId;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link CodingType }
     *     
     */
    public CodingType getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodingType }
     *     
     */
    public void setUnit(CodingType value) {
        this.unit = value;
    }

    /**
     * Gets the value of the measurePopulationDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurePopulationDefinition() {
        return measurePopulationDefinition;
    }

    /**
     * Sets the value of the measurePopulationDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurePopulationDefinition(String value) {
        this.measurePopulationDefinition = value;
    }

    /**
     * Gets the value of the measurePopulationInclusionValueSetId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measurePopulationInclusionValueSetId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasurePopulationInclusionValueSetId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMeasurePopulationInclusionValueSetId() {
        if (measurePopulationInclusionValueSetId == null) {
            measurePopulationInclusionValueSetId = new ArrayList<String>();
        }
        return this.measurePopulationInclusionValueSetId;
    }

    /**
     * Gets the value of the measurePopulationExclusionValueSetId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measurePopulationExclusionValueSetId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasurePopulationExclusionValueSetId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMeasurePopulationExclusionValueSetId() {
        if (measurePopulationExclusionValueSetId == null) {
            measurePopulationExclusionValueSetId = new ArrayList<String>();
        }
        return this.measurePopulationExclusionValueSetId;
    }

    /**
     * Gets the value of the cohortDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCohortDefinition() {
        return cohortDefinition;
    }

    /**
     * Sets the value of the cohortDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCohortDefinition(String value) {
        this.cohortDefinition = value;
    }

    /**
     * Gets the value of the cohortInclusionValueSetsId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cohortInclusionValueSetsId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCohortInclusionValueSetsId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCohortInclusionValueSetsId() {
        if (cohortInclusionValueSetsId == null) {
            cohortInclusionValueSetsId = new ArrayList<String>();
        }
        return this.cohortInclusionValueSetsId;
    }

    /**
     * Gets the value of the cohortExclusionValueSetsId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cohortExclusionValueSetsId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCohortExclusionValueSetsId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCohortExclusionValueSetsId() {
        if (cohortExclusionValueSetsId == null) {
            cohortExclusionValueSetsId = new ArrayList<String>();
        }
        return this.cohortExclusionValueSetsId;
    }

    /**
     * Gets the value of the regionalAffinityCalculation property.
     * 
     * @return
     *     possible object is
     *     {@link CodingType }
     *     
     */
    public CodingType getRegionalAffinityCalculation() {
        return regionalAffinityCalculation;
    }

    /**
     * Sets the value of the regionalAffinityCalculation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodingType }
     *     
     */
    public void setRegionalAffinityCalculation(CodingType value) {
        this.regionalAffinityCalculation = value;
    }

    /**
     * Gets the value of the thresholdForViewing property.
     * 
     */
    public int getThresholdForViewing() {
        return thresholdForViewing;
    }

    /**
     * Sets the value of the thresholdForViewing property.
     * 
     */
    public void setThresholdForViewing(int value) {
        this.thresholdForViewing = value;
    }

    /**
     * Gets the value of the measuringFrequency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measuringFrequency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasuringFrequency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodingType }
     * 
     * 
     */
    public List<CodingType> getMeasuringFrequency() {
        if (measuringFrequency == null) {
            measuringFrequency = new ArrayList<CodingType>();
        }
        return this.measuringFrequency;
    }

    /**
     * Gets the value of the organizationLevel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizationLevel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganizationLevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodingType }
     * 
     * 
     */
    public List<CodingType> getOrganizationLevel() {
        if (organizationLevel == null) {
            organizationLevel = new ArrayList<CodingType>();
        }
        return this.organizationLevel;
    }

    /**
     * Gets the value of the interpretationTextPersonell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterpretationTextPersonell() {
        return interpretationTextPersonell;
    }

    /**
     * Sets the value of the interpretationTextPersonell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterpretationTextPersonell(String value) {
        this.interpretationTextPersonell = value;
    }

    /**
     * Gets the value of the interpretationTextPublic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterpretationTextPublic() {
        return interpretationTextPublic;
    }

    /**
     * Sets the value of the interpretationTextPublic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterpretationTextPublic(String value) {
        this.interpretationTextPublic = value;
    }

    /**
     * Gets the value of the availableReportingSystemHsaId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the availableReportingSystemHsaId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvailableReportingSystemHsaId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAvailableReportingSystemHsaId() {
        if (availableReportingSystemHsaId == null) {
            availableReportingSystemHsaId = new ArrayList<String>();
        }
        return this.availableReportingSystemHsaId;
    }

    /**
     * Gets the value of the serviceContractVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getServiceContractVersion() {
        return serviceContractVersion;
    }

    /**
     * Sets the value of the serviceContractVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setServiceContractVersion(Integer value) {
        this.serviceContractVersion = value;
    }

}
