//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 03:50:40 PM CEST 
//


package opendata.followup.groupoutcomes.qualitymeasures._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubCategoryDefinitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubCategoryDefinitionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="parentMeasureId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}MeasureIdType"/&gt;
 *         &lt;element name="subCategoryCode" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubCategoryDefinitionType", propOrder = {
    "parentMeasureId",
    "subCategoryCode"
})
public class SubCategoryDefinitionType {

    @XmlElement(required = true)
    protected String parentMeasureId;
    @XmlElement(required = true)
    protected List<CodingType> subCategoryCode;

    /**
     * Gets the value of the parentMeasureId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentMeasureId() {
        return parentMeasureId;
    }

    /**
     * Sets the value of the parentMeasureId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentMeasureId(String value) {
        this.parentMeasureId = value;
    }

    /**
     * Gets the value of the subCategoryCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subCategoryCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubCategoryCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodingType }
     * 
     * 
     */
    public List<CodingType> getSubCategoryCode() {
        if (subCategoryCode == null) {
            subCategoryCode = new ArrayList<CodingType>();
        }
        return this.subCategoryCode;
    }

}
