//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 03:50:40 PM CEST 
//


package opendata.followup.groupoutcomes.qualitymeasures._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TargetMeasurementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TargetMeasurementType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="targetId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}TargetIdType"/&gt;
 *         &lt;element name="validFrom" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="validTo" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="targetName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="targetDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="targetType" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}CodingType"/&gt;
 *         &lt;element name="targetMeasureId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}MeasureIdType"/&gt;
 *         &lt;element name="targetOrganizationId" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}PerformingOrganizationIdType"/&gt;
 *         &lt;element name="authoringOrganization" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="targetProportionMeasure" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}TargetProportionMeasureType" minOccurs="0"/&gt;
 *         &lt;element name="targetContinuousMeasure" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}TargetContinuousMeasureType" minOccurs="0"/&gt;
 *         &lt;element name="targetCohortMeasure" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}TargetCohortMeasureType" minOccurs="0"/&gt;
 *         &lt;element name="author" type="{urn:opendata:followup:groupoutcomes:qualitymeasures:2}AuthorType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TargetMeasurementType", propOrder = {
    "targetId",
    "validFrom",
    "validTo",
    "targetName",
    "targetDescription",
    "targetType",
    "targetMeasureId",
    "targetOrganizationId",
    "authoringOrganization",
    "targetProportionMeasure",
    "targetContinuousMeasure",
    "targetCohortMeasure",
    "author"
})
@XmlSeeAlso({
    TargetMeasurement.class
})
public class TargetMeasurementType {

    @XmlElement(required = true)
    protected String targetId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar validFrom;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar validTo;
    @XmlElement(required = true)
    protected String targetName;
    @XmlElement(required = true)
    protected String targetDescription;
    @XmlElement(required = true)
    protected CodingType targetType;
    @XmlElement(required = true)
    protected String targetMeasureId;
    @XmlElement(required = true)
    protected String targetOrganizationId;
    @XmlElement(required = true)
    protected String authoringOrganization;
    protected TargetProportionMeasureType targetProportionMeasure;
    protected TargetContinuousMeasureType targetContinuousMeasure;
    protected TargetCohortMeasureType targetCohortMeasure;
    @XmlElement(required = true)
    protected AuthorType author;

    /**
     * Gets the value of the targetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * Sets the value of the targetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetId(String value) {
        this.targetId = value;
    }

    /**
     * Gets the value of the validFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidFrom() {
        return validFrom;
    }

    /**
     * Sets the value of the validFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidFrom(XMLGregorianCalendar value) {
        this.validFrom = value;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidTo() {
        return validTo;
    }

    /**
     * Sets the value of the validTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidTo(XMLGregorianCalendar value) {
        this.validTo = value;
    }

    /**
     * Gets the value of the targetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * Sets the value of the targetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetName(String value) {
        this.targetName = value;
    }

    /**
     * Gets the value of the targetDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetDescription() {
        return targetDescription;
    }

    /**
     * Sets the value of the targetDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetDescription(String value) {
        this.targetDescription = value;
    }

    /**
     * Gets the value of the targetType property.
     * 
     * @return
     *     possible object is
     *     {@link CodingType }
     *     
     */
    public CodingType getTargetType() {
        return targetType;
    }

    /**
     * Sets the value of the targetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodingType }
     *     
     */
    public void setTargetType(CodingType value) {
        this.targetType = value;
    }

    /**
     * Gets the value of the targetMeasureId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetMeasureId() {
        return targetMeasureId;
    }

    /**
     * Sets the value of the targetMeasureId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetMeasureId(String value) {
        this.targetMeasureId = value;
    }

    /**
     * Gets the value of the targetOrganizationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetOrganizationId() {
        return targetOrganizationId;
    }

    /**
     * Sets the value of the targetOrganizationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetOrganizationId(String value) {
        this.targetOrganizationId = value;
    }

    /**
     * Gets the value of the authoringOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthoringOrganization() {
        return authoringOrganization;
    }

    /**
     * Sets the value of the authoringOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthoringOrganization(String value) {
        this.authoringOrganization = value;
    }

    /**
     * Gets the value of the targetProportionMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link TargetProportionMeasureType }
     *     
     */
    public TargetProportionMeasureType getTargetProportionMeasure() {
        return targetProportionMeasure;
    }

    /**
     * Sets the value of the targetProportionMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetProportionMeasureType }
     *     
     */
    public void setTargetProportionMeasure(TargetProportionMeasureType value) {
        this.targetProportionMeasure = value;
    }

    /**
     * Gets the value of the targetContinuousMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link TargetContinuousMeasureType }
     *     
     */
    public TargetContinuousMeasureType getTargetContinuousMeasure() {
        return targetContinuousMeasure;
    }

    /**
     * Sets the value of the targetContinuousMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetContinuousMeasureType }
     *     
     */
    public void setTargetContinuousMeasure(TargetContinuousMeasureType value) {
        this.targetContinuousMeasure = value;
    }

    /**
     * Gets the value of the targetCohortMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link TargetCohortMeasureType }
     *     
     */
    public TargetCohortMeasureType getTargetCohortMeasure() {
        return targetCohortMeasure;
    }

    /**
     * Sets the value of the targetCohortMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetCohortMeasureType }
     *     
     */
    public void setTargetCohortMeasure(TargetCohortMeasureType value) {
        this.targetCohortMeasure = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorType }
     *     
     */
    public AuthorType getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorType }
     *     
     */
    public void setAuthor(AuthorType value) {
        this.author = value;
    }

}
